(function () {
'use strict';
var $ = function (id) { return document.getElementById(id); };
var state = {view:'catalog',page:1,items:[],details:null,season:1,episodePage:0,audio:'sub',generation:0,playing:null,sourceMode:'auto',restore:null};
var video=$('video'), hudTimer,nextTimer=null,nextRemaining=0,autoNext=localStorage.getItem('autoNext')!=='false';
function showKey(t){return t.provider+':'+t.id;}
function showPref(t){try{return JSON.parse(localStorage.getItem('showPreferences')||'{}')[showKey(t)]||{};}catch(e){return {};}}
function rememberShow(t,key,value){var all;try{all=JSON.parse(localStorage.getItem('showPreferences')||'{}');}catch(e){all={};}var pref=all[showKey(t)]||{};pref[key]=value;all[showKey(t)]=pref;localStorage.setItem('showPreferences',JSON.stringify(all));}
function watchedKey(t,e){return showKey(t)+':'+e.season+':'+e.number;}
function isWatched(t,e){return stored('watched').indexOf(watchedKey(t,e))>=0;}
function markWatched(t,e,value,automatic){if(automatic && state.playing && state.playing.ignoreWatched)return;var key=watchedKey(t,e),list=stored('watched').filter(function(k){return k!==key;});if(value)list.push(key);localStorage.setItem('watched',JSON.stringify(list));if(value)localStorage.setItem(positionKey(t,e),'0');if(!automatic && state.playing && same(state.playing.title,t))state.playing.ignoreWatched=!value;}
function switchPlaybackPreference(key,value){if(!state.playing)return;rememberShow(state.playing.title,key,value);playbackOptionLabels();savePosition();state.restore={time:state.restore?state.restore.time:video.currentTime,running:state.restore?state.restore.running:!video.paused};video.pause();state.sourceMode=showPref(state.playing.title).source||'auto';play(state.playing.episode);}
function playbackStatus(text){$('playbackStatus').textContent=text||'';$('playbackStatus').hidden=!text;}
var subtitleDelay=Number(localStorage.getItem('subtitleDelay')||0);if(!isFinite(subtitleDelay)||Math.abs(subtitleDelay)>10)subtitleDelay=0;
var cueTimes=new WeakMap();
function captionTracks(){return Array.prototype.filter.call(video.textTracks||[],function(t){return t.kind==='subtitles'||t.kind==='captions';});}
function applyCaptionTiming(){captionTracks().forEach(function(t){Array.prototype.forEach.call(t.cues||[],function(c){var original=cueTimes.get(c);if(!original){original={start:c.startTime,end:c.endTime,delay:null};cueTimes.set(c,original);}if(original.delay===subtitleDelay)return;original.delay=subtitleDelay;c.startTime=Math.max(0,original.start+subtitleDelay);c.endTime=Math.max(c.startTime+.01,original.end+subtitleDelay);});});}
function playbackOptionLabels(){var active=captionTracks().find(function(t){return t.mode==='showing';});$('subtitleTrack').textContent='Subtitle track: '+(active?active.label||active.language:'Off');var audio=video.audioTracks;var selected=audio && Array.prototype.find.call(audio,function(t){return t.enabled;});$('audioTrack').textContent='Audio track: '+(selected?selected.label||selected.language||'Default':'Provider default');$('audioTrack').disabled=!audio||audio.length<2;$('subtitleTiming').textContent='Subtitle timing: '+subtitleDelay.toFixed(1)+' seconds';$('autoNext').textContent='Auto next episode: '+(autoNext?'On':'Off');var pref=state.playing?showPref(state.playing.title):{};$('streamSource').textContent='Source: '+(pref.source||'auto');$('streamSource').disabled=!state.playing||state.playing.title.provider!=='luffy';$('videoQuality').textContent='Quality: '+(pref.height?pref.height+'p':'Auto')+' · current '+(video.videoHeight||'—')+'p';$('videoQuality').disabled=!state.playing;$('watchedToggle').textContent=state.playing&&isWatched(state.playing.title,state.playing.episode)?'Mark unwatched':'Mark watched';$('watchedToggle').disabled=!state.playing;}
function adjustTiming(amount){subtitleDelay=Math.max(-10,Math.min(10,subtitleDelay+amount));localStorage.setItem('subtitleDelay',String(subtitleDelay));applyCaptionTiming();playbackOptionLabels();}
function nextEpisode(){if(!state.playing||!state.details)return null;var eps=state.details.episodes,index=eps.findIndex(function(e){return e.season===state.playing.episode.season && e.number===state.playing.episode.number;});return index>=0?eps[index+1]||null:null;}
function cancelNext(){clearInterval(nextTimer);nextTimer=null;$('nextUp').hidden=true;}
function startNext(){var ep=nextEpisode();cancelNext();if(ep)play(ep);}
function ended(){savePosition();if(!autoNext||!nextEpisode())return stop();cancelNext();nextRemaining=8;$('nextUp').hidden=false;$('nextMessage').textContent='Next episode in 8 seconds';$('cancelNext').focus();nextTimer=setInterval(function(){nextRemaining--;$('nextMessage').textContent='Next episode in '+nextRemaining+' seconds';if(nextRemaining<=0)startNext();},1000);}

function applyTextSize(){var extra=localStorage.getItem('uiTextSize')==='extra';document.body.classList.toggle('extraText',extra);if($('textSize'))$('textSize').textContent=extra?'Standard text':'Larger text';}
applyTextSize();if($('textSize'))$('textSize').onclick=function(){localStorage.setItem('uiTextSize',document.body.classList.contains('extraText')?'large':'extra');applyTextSize();};
var subtitleSizes=[32,40,48,56,64,72],subtitleColors=[{name:'White',value:'#ffffff'},{name:'Yellow',value:'#ffeb3b'},{name:'Mint',value:'#73e0c1'},{name:'Cyan',value:'#80deff'}];
var subtitleSize=Number(localStorage.getItem('subtitleSize')||48),subtitleColor=localStorage.getItem('subtitleColor')||'#ffffff',subtitleReturnFocus=null;
if(subtitleSizes.indexOf(subtitleSize)<0)subtitleSize=48;
if(!subtitleColors.some(function(c){return c.value===subtitleColor;}))subtitleColor='#ffffff';
function applySubtitles(){
    var color=subtitleColors.find(function(c){return c.value===subtitleColor;});
    $('subtitleStyle').textContent='#video::cue{font-size:'+subtitleSize+'px;color:'+subtitleColor+';background:rgba(0,0,0,.7)}';
    $('subtitleSize').textContent='Size: '+subtitleSize+' px · OK to change';$('subtitleColor').textContent='Color: '+color.name+' · OK to change';
    $('subtitlePreview').style.fontSize=subtitleSize+'px';$('subtitlePreview').style.color=subtitleColor;
}
function openSubtitles(){playbackOptionLabels();subtitleReturnFocus=document.activeElement;$('subtitleSettings').hidden=false;clearTimeout(hudTimer);applySubtitles();$('subtitleSize').focus();}
function closeSubtitles(){$('subtitleSettings').hidden=true;if(subtitleReturnFocus && document.contains(subtitleReturnFocus))subtitleReturnFocus.focus();if(state.playing)showHud();}
$('subtitleSize').onclick=function(){subtitleSize=subtitleSizes[(subtitleSizes.indexOf(subtitleSize)+1)%subtitleSizes.length];localStorage.setItem('subtitleSize',String(subtitleSize));applySubtitles();};
$('subtitleColor').onclick=function(){var i=subtitleColors.findIndex(function(c){return c.value===subtitleColor;});subtitleColor=subtitleColors[(i+1)%subtitleColors.length].value;localStorage.setItem('subtitleColor',subtitleColor);applySubtitles();};
$('subtitleTrack').onclick=function(){var tracks=captionTracks(),active=tracks.findIndex(function(t){return t.mode==='showing';});tracks.forEach(function(t){t.mode='hidden';});if(active+1<tracks.length)tracks[active+1].mode='showing';var picked=tracks.find(function(t){return t.mode==='showing';});if(state.playing){rememberShow(state.playing.title,'subtitleOff',!picked);if(picked){rememberShow(state.playing.title,'subtitleLanguage',picked.language||'und');rememberShow(state.playing.title,'subtitleLabel',picked.label||'');}}playbackOptionLabels();};
$('audioTrack').onclick=function(){var tracks=video.audioTracks;if(!tracks||!tracks.length)return;var i=Array.prototype.findIndex.call(tracks,function(t){return t.enabled;});for(var n=0;n<tracks.length;n++)tracks[n].enabled=n===(i+1)%tracks.length;if(state.playing){rememberShow(state.playing.title,'audioLanguage',tracks[(i+1)%tracks.length].language||'und');rememberShow(state.playing.title,'audioLabel',tracks[(i+1)%tracks.length].label||'Track '+((i+1)%tracks.length+1));}playbackOptionLabels();};
$('subtitleEarlier').onclick=function(){adjustTiming(-.5);};$('subtitleLater').onclick=function(){adjustTiming(.5);};$('subtitleReset').onclick=function(){adjustTiming(-subtitleDelay);};$('autoNext').onclick=function(){autoNext=!autoNext;localStorage.setItem('autoNext',String(autoNext));playbackOptionLabels();};
$('streamSource').onclick=function(){var values=['auto','cinejoy','vixsrc','lookmovie'],pref=showPref(state.playing.title);switchPlaybackPreference('source',values[(values.indexOf(pref.source||'auto')+1)%values.length]);};
$('videoQuality').onclick=function(){var choices=[0].concat(state.playing.heights||[]),current=showPref(state.playing.title).height||0;switchPlaybackPreference('height',choices[(choices.indexOf(current)+1)%choices.length]);};
$('watchedToggle').onclick=function(){markWatched(state.playing.title,state.playing.episode,!isWatched(state.playing.title,state.playing.episode),false);playbackOptionLabels();};
$('cancelNext').onclick=cancelNext;$('playNext').onclick=startNext;$('nextEpisode').onclick=startNext;
$('subtitleDone').onclick=closeSubtitles;$('subtitleOptions').onclick=openSubtitles;applySubtitles();
function api(path,params) {
    if(window.ANI_TEST_API) return window.ANI_TEST_API(path,params);
    return new Promise(function(resolve,reject) {
        if(!window.webOS || !webOS.service) return reject(new Error('This app connects through its webOS catalog service.'));
        webOS.service.request('luna://dev.anidroid.tv.service',{method:'request',parameters:{path:path,params:params||{}},onSuccess:function(r){resolve(r.data);},onFailure:function(r){reject(new Error(r.errorText||'Catalog unavailable.'));}});
    });
}
function message(text,error){$('message').textContent=text||'';$('message').className=error?'error':'';}
function node(tag,text,cls){var e=document.createElement(tag);if(text)e.textContent=text;if(cls)e.className=cls;return e;}
function button(text,action,cls){var b=node('button',text,cls);b.onclick=action;return b;}
function stored(key){try{return JSON.parse(localStorage.getItem(key)||'[]');}catch(e){return [];}}
function favorites(){return stored('favorites');}
function same(a,b){return a.provider===b.provider && a.id===b.id;}
function focusFirst(){var e=$('content').querySelector('button,select');if(e)e.focus();}
function genreOptions(genres){var value=$('genre').value;$('genre').textContent='';var all=node('option','All genres');all.value='';$('genre').appendChild(all);(genres||[]).forEach(function(g){var o=node('option',g.name+' ('+g.count+')');o.value=g.name;$('genre').appendChild(o);});$('genre').value=value;}
function catalog(next){
    var generation=++state.generation;state.view='catalog';$('filters').hidden=false;state.details=null;$('query').placeholder='Search catalog';var page=next?state.page+1:1;message('Loading catalog…');
    api('/v1/catalog',{q:$('query').value,provider:$('source').value,kind:$('kind').value,genre:$('genre').value,page:page,sort:$('sort').value}).then(function(r){
        if(generation!==state.generation)return;state.page=page;state.items=next?state.items.concat(r.items):r.items;genreOptions(r.genres);renderCards(state.items,r.hasMore,function(){catalog(true);});
        var coverage=r.coverage||{};message(r.total+' matching titles · '+(coverage.tagged||0)+' of '+(coverage.total||r.total)+' indexed titles categorized');
    }).catch(function(e){if(generation===state.generation)message(e.message,true);});
}
function live(next){
    state.view='search';state.details=null;$('filters').hidden=false;if($('source').value==='all')$('source').value='ani';$('query').placeholder='Search anime, movies or series';
    if(!$('query').value.trim()){$('content').textContent='';message('Enter a title to search.');$('query').focus();return;}
    var generation=++state.generation;var page=next?state.page+1:1;var provider=$('source').value==='all'?'ani':$('source').value;message('Searching '+(provider==='ani'?'ani-cli':'Luffy')+'…');
    api('/v1/search',{provider:provider,q:$('query').value,page:page}).then(function(r){if(generation!==state.generation)return;state.page=page;state.items=next?state.items.concat(r.items):r.items;renderCards(state.items,r.hasMore,function(){live(true);});message(r.items.length?'Choose a title.':'No matching titles.');}).catch(function(e){message(e.message,true);});
}
function recentPlays(){return stored('recentPlays').filter(function(p){return Number(localStorage.getItem(positionKey(p.title,p.episode))||0)>0 && !isWatched(p.title,p.episode);});}
function resumeSaved(saved){message('Refreshing your saved episode…');api('/v1/details',{provider:saved.title.provider,id:saved.title.id}).then(function(d){state.details=d;state.audio=showPref(saved.title).audio||saved.audio||'sub';state.sourceMode=showPref(saved.title).source||'auto';var ep=d.episodes.find(function(e){return e.season===saved.episode.season && e.number===saved.episode.number;});if(!ep)throw new Error('Saved episode is no longer listed.');play(ep);}).catch(function(e){message(e.message,true);});}
function continueRow(){var row=node('div',null,'continueRow'),entries=recentPlays();if(entries.length){row.appendChild(node('h2','Continue Watching'));entries.forEach(function(p){row.appendChild(button(p.title.name+' · '+(p.episode.season?'Episode '+p.episode.number:'Movie'),function(){resumeSaved(p);}));});}return row;}
function showContinue(){state.view='continue';state.details=null;$('filters').hidden=true;$('content').textContent='';$('content').appendChild(continueRow());message(recentPlays().length?'Saved on this TV.':'Start watching to save your place.');focusFirst();}
function showWatchlist(){state.view='watchlist';state.details=null;$('filters').hidden=true;message('Watchlist saved on this TV.');renderCards(stored('watchlist'),false);}
function renderCards(items,more,load){
    $('content').textContent='';if(state.view==='catalog')$('content').appendChild(continueRow());var grid=node('div',null,'grid');$('content').appendChild(grid);
    items.forEach(function(t){var card=button('',function(){open(t);},'card');var poster=node('div',t.name.slice(0,1),'poster');if(/^https:\/\//.test(t.poster||'')){var img=document.createElement('img');img.src=t.poster;img.alt='';img.onerror=function(){poster.textContent=t.name.slice(0,1);};poster.textContent='';poster.appendChild(img);}card.appendChild(poster);var text=node('div',null,'cardText');text.appendChild(node('small',t.provider==='ani'?'ANI-CLI':'LUFFY','provider'));text.appendChild(node('strong',t.name));text.appendChild(node('small',t.info));card.appendChild(text);grid.appendChild(card);});
    if(!items.length)$('content').appendChild(node('div','Nothing here yet. Try another filter or refresh the catalog.','empty'));
    if(more)$('content').appendChild(button('Load more',load,'loadMore'));focusFirst();
}
function open(title){var generation=++state.generation;message('Loading episodes…');api('/v1/details',{provider:title.provider,id:title.id}).then(function(d){if(generation!==state.generation)return;state.details=d;state.season=d.episodes.length?d.episodes[0].season:1;state.episodePage=0;var pref=showPref(d.title);state.audio=pref.audio|| (d.audio.length?d.audio[0].id:'sub');state.sourceMode=pref.source||'auto';renderDetails();message(d.stale?'Saved episode list; provider refresh is currently unavailable.':'');}).catch(function(e){message(e.message,true);});}
function renderDetails(){
    var d=state.details;if(!d)return;$('filters').hidden=true;$('content').textContent='';var panel=node('div',null,'detail');$('content').appendChild(panel);panel.appendChild(button('‹ Back',back));panel.appendChild(node('h2',d.title.name));panel.appendChild(node('p',(d.title.genres||[]).join(' · ')));
    if(d.description)panel.appendChild(node('p',d.description));var actions=node('div',null,'actions');panel.appendChild(actions);
    actions.appendChild(button('Subtitle options',openSubtitles));
    var listed=stored('watchlist').some(function(t){return same(t,d.title);});actions.appendChild(button(listed?'✓ Watchlist':'+ Watchlist',function(){var values=stored('watchlist').filter(function(t){return !same(t,d.title);});if(!listed)values.unshift(d.title);localStorage.setItem('watchlist',JSON.stringify(values));renderDetails();}));
    var saved=favorites().some(function(t){return same(t,d.title);});actions.appendChild(button(saved?'♥ Saved':'♡ Favorite',function(){var values=favorites().filter(function(t){return !same(t,d.title);});if(!saved)values.unshift(d.title);localStorage.setItem('favorites',JSON.stringify(values));renderDetails();}));
    var seasons=[];d.episodes.forEach(function(e){if(seasons.indexOf(e.season)<0)seasons.push(e.season);});
    if(d.title.series){var select=document.createElement('select');select.setAttribute('aria-label','Season');seasons.forEach(function(n){var o=node('option','Season '+n);o.value=n;select.appendChild(o);});select.value=state.season;select.onchange=function(){state.season=Number(select.value);state.episodePage=0;renderDetails();};actions.appendChild(select);}
    if(d.audio.length>1){var audio=document.createElement('select');audio.setAttribute('aria-label','Audio');d.audio.forEach(function(a){var o=node('option',a.label);o.value=a.id;audio.appendChild(o);});audio.value=state.audio;audio.onchange=function(){state.audio=audio.value;rememberShow(d.title,'audio',audio.value);};actions.appendChild(audio);}
    var episodes=d.episodes.filter(function(e){return e.season===state.season;});var grid=node('div',null,'episodes');panel.appendChild(grid);episodes.slice(state.episodePage*60,(state.episodePage+1)*60).forEach(function(e){var cell=node('div');cell.appendChild(button(e.season===0?'Play movie':'Episode '+e.number+(e.name?' · '+e.name:''),function(){play(e);}));cell.appendChild(button(isWatched(d.title,e)?'✓ Watched':'Mark watched',function(){markWatched(d.title,e,!isWatched(d.title,e),false);renderDetails();}));grid.appendChild(cell);});
    if(state.episodePage>0)panel.appendChild(button('Previous episodes',function(){state.episodePage--;renderDetails();},'loadMore'));
    if((state.episodePage+1)*60<episodes.length)panel.appendChild(button('More episodes',function(){state.episodePage++;renderDetails();},'loadMore'));focusFirst();
}
function positionKey(t,e){return 'position:'+t.provider+':'+t.id+':'+e.season+':'+e.number;}
function play(ep){
    cancelNext();var title=state.details.title,generation=++state.generation;message('Finding a stream…');
    playbackStatus('Finding a stream…');api('/v1/streams',{provider:title.provider,id:title.id,season:ep.season,episode:ep.number,audio:state.audio,source:state.sourceMode,height:showPref(title).height||0,tv:true}).then(function(r){
        if(generation!==state.generation)return;var preferredHeight=showPref(title).height||0;var stream=r.streams.find(function(s){return s.height===preferredHeight && s.tvUrl;}) || r.streams.find(function(s){return s.tvUrl;});if(!stream)throw new Error('No TV stream available.');
        state.playing={title:title,episode:ep,audio:state.audio,sources:stream.sources||[stream.label],captionsPending:(stream.captions||[]).length,heights:stream.heights||r.streams.map(function(s){return s.height;}).filter(function(h){return h>0;})};$('playingTitle').textContent=title.name+(ep.season?' · Episode '+ep.number:'');$('playback').hidden=false;$('videoError').hidden=true;message('');
        while(video.firstChild)video.removeChild(video.firstChild);
        var pref=showPref(title),captions=stream.captions||[],preferred=captions.findIndex(function(c){return pref.subtitleLabel?c.name===pref.subtitleLabel:/English/i.test(c.name);});if(preferred<0)preferred=0;
        var activePlayback=state.playing;
        captions.forEach(function(c,i){if(!c.tvUrl)return;var track=document.createElement('track');track.kind='subtitles';track.label=c.name;track.srclang=/English/i.test(c.name)?'en':'und';track.src=c.tvUrl;track.default=i===preferred && !pref.subtitleOff;track.onload=function(){if(state.playing!==activePlayback)return;activePlayback.captionsPending=Math.max(0,activePlayback.captionsPending-1);track.track.mode=i===preferred && !pref.subtitleOff?'showing':'hidden';applyCaptionTiming();playbackOptionLabels();if(video.readyState>=3)playbackStatus(activePlayback.captionsPending?'Loading subtitles…':'');};track.onerror=function(){if(state.playing!==activePlayback)return;activePlayback.captionsPending=Math.max(0,activePlayback.captionsPending-1);if(video.readyState>=3)playbackStatus(activePlayback.captionsPending?'Loading subtitles…':'');};video.appendChild(track);});
        $('nextEpisode').disabled=!nextEpisode();
        video.src=stream.tvUrl;video.load();playbackStatus('Buffering video…');var started=(!state.restore||state.restore.running)?video.play():null;if(started && started.catch)started.catch(function(){showVideoError('Press OK to start playback.');});showHud();
    }).catch(function(e){playbackStatus('');message(e.message,true);var retry=button('Retry stream',function(){play(ep);});if(state.playing)showVideoError(e.message);else $('content').prepend(retry);});
}
function showVideoError(text){var panel=$('videoError');panel.textContent=text;if(state.playing){panel.appendChild(node('p',state.playing.sources.join(' · ')));panel.appendChild(button('Retry fresh stream',function(){savePosition();play(state.playing.episode);}));panel.appendChild(button('Back to episodes',stop));}panel.hidden=false;showHud();var first=panel.querySelector('button');if(first)first.focus();}
function savePosition(){if(!state.playing)return;var entries=stored('recentPlays').filter(function(p){return !same(p.title,state.playing.title);});entries.unshift({title:state.playing.title,episode:state.playing.episode,audio:state.playing.audio});localStorage.setItem('recentPlays',JSON.stringify(entries.slice(0,30)));var p=video.currentTime||0;if(video.duration>0 && p/video.duration>.95){markWatched(state.playing.title,state.playing.episode,true,true);p=0;}localStorage.setItem(positionKey(state.playing.title,state.playing.episode),String(p));}
function stop(){playbackStatus('');cancelNext();$('subtitleSettings').hidden=true;savePosition();video.pause();video.removeAttribute('src');video.load();$('playback').hidden=true;state.playing=null;clearTimeout(hudTimer);renderDetails();}
function showHud(){$('videoHud').hidden=false;clearTimeout(hudTimer);hudTimer=setTimeout(function(){$('videoHud').hidden=true;},3500);}
function back(){++state.generation;if(state.playing)return stop();if(state.details){state.details=null;$('filters').hidden=false;if(state.view==='favorites')return showFavorites();if(state.view==='watchlist')return showWatchlist();if(state.view==='continue')return showContinue();return state.view==='search'?live(false):catalog(false);}if(window.webOS && webOS.platformBack)webOS.platformBack();}
function showFavorites(){state.view='favorites';state.details=null;$('filters').hidden=true;message('Favorites saved on this TV.');renderCards(favorites(),false);}
video.addEventListener('loadedmetadata',function(){if(state.playing){var pref=showPref(state.playing.title),audio=video.audioTracks;if(audio){var wanted=pref.audioLanguage||'en',match=Array.prototype.find.call(audio,function(t){return pref.audioLabel?t.label===pref.audioLabel:t.language && t.language.slice(0,2)===wanted.slice(0,2);});if(match)Array.prototype.forEach.call(audio,function(t){t.enabled=t===match;});}playbackOptionLabels();if(state.restore){var restore=state.restore;state.restore=null;video.currentTime=restore.time;if(restore.running)video.play();else video.pause();return;}var p=Number(localStorage.getItem(positionKey(state.playing.title,state.playing.episode))||0);if(p>0 && p<video.duration)video.currentTime=p;}});
video.addEventListener('waiting',function(){if(state.playing)playbackStatus('Buffering video…');});video.addEventListener('playing',function(){playbackStatus(state.playing && state.playing.captionsPending?'Loading subtitles…':'');});video.addEventListener('canplay',function(){playbackStatus(state.playing && state.playing.captionsPending?'Loading subtitles…':'');});
video.addEventListener('error',function(){if(state.playing)showVideoError('Playback failed. Press Back and try another episode or source.');});
video.addEventListener('ended',ended);video.addEventListener('timeupdate',applyCaptionTiming);setInterval(savePosition,5000);document.addEventListener('visibilitychange',function(){if(document.hidden && state.playing){savePosition();video.pause();}});
$('stop').onclick=stop;$('catalogTab').onclick=function(){catalog(false);};$('searchTab').onclick=function(){live(false);};$('favoritesTab').onclick=showFavorites;$('watchlistTab').onclick=showWatchlist;$('continueTab').onclick=showContinue;$('sort').onchange=function(){catalog(false);};$('refresh').onclick=function(){catalog(false);};$('search').onclick=function(){state.view==='search'?live(false):catalog(false);};$('query').onkeydown=function(e){if(e.keyCode===13){e.preventDefault();$('search').click();}};
$('source').onchange=$('kind').onchange=function(){$('genre').value='';state.view==='search'?live(false):catalog(false);};$('genre').onchange=function(){catalog(false);};$('connection').onclick=function(){api('/v1/status',{}).then(function(){message('Connected to your catalog server. Video is streamed through a private LAN relay.');}).catch(function(e){message(e.message,true);});};
function cleanBackupTitle(t){if(!t||['ani','luffy'].indexOf(t.provider)<0||! /^[A-Za-z0-9_-]{1,200}$/.test(t.id)||typeof t.name!=='string'||t.name.length>500)throw new Error('Invalid title.');return {provider:t.provider,id:t.id,name:t.name,info:String(t.info||'').slice(0,500),series:t.series!==false,genres:Array.isArray(t.genres)?t.genres:[],poster:''};}
function exportLibrary(){var shows;try{shows=JSON.parse(localStorage.getItem('showPreferences')||'{}');}catch(e){shows={};}return JSON.stringify({schema:1,lists:{favorites:stored('favorites').map(cleanBackupTitle),watchlist:stored('watchlist').map(cleanBackupTitle),history:stored('recentPlays').map(function(p){return cleanBackupTitle(p.title);})},preferences:{subtitleSize:subtitleSize/2,subtitleColor:(parseInt(subtitleColor.slice(1),16)|0xff000000),subtitleDelayMs:Math.round(subtitleDelay*1000),autoNext:autoNext},shows:shows,watched:stored('watched')},null,2);}
function importLibrary(text){
    if(text.length>2*1024*1024)throw new Error('Backup is too large.');var data=JSON.parse(text);
    if(data.schema!==1||Object.keys(data).some(function(k){return ['schema','lists','preferences','shows','watched'].indexOf(k)<0;}))throw new Error('Unsupported backup.');
    var lists={};['favorites','watchlist','history'].forEach(function(key){var rows=data.lists[key];if(!Array.isArray(rows)||rows.length>1000)throw new Error('Invalid lists.');lists[key]=rows.map(cleanBackupTitle);});
    var p=data.preferences||{},allowed=['subtitleSize','subtitleColor','subtitleDelayMs','autoNext','wifiOnly','queuePaused','downloadHeight'];if(Object.keys(p).some(function(k){return allowed.indexOf(k)<0;}))throw new Error('Unsupported preference.');
    if(p.subtitleSize!==undefined && [16,20,24,28,32,36].indexOf(p.subtitleSize)<0)throw new Error('Invalid subtitle size.');
    if(p.subtitleColor!==undefined && [-1,(0xffffeb3b|0),(0xff73e0c1|0),(0xff80deff|0)].indexOf(p.subtitleColor)<0)throw new Error('Invalid subtitle color.');
    if(p.subtitleDelayMs!==undefined && (!Number.isFinite(p.subtitleDelayMs)||Math.abs(p.subtitleDelayMs)>10000))throw new Error('Invalid timing.');
    ['autoNext','wifiOnly','queuePaused'].forEach(function(k){if(p[k]!==undefined && typeof p[k]!=='boolean')throw new Error('Invalid option.');});
    var shows=data.shows;if(!shows||typeof shows!=='object'||Array.isArray(shows)||Object.keys(shows).length>1000)throw new Error('Invalid show preferences.');
    Object.keys(shows).forEach(function(k){var v=shows[k];if(! /^(ani|luffy):[A-Za-z0-9_-]{1,200}$/.test(k)||!v||Object.keys(v).some(function(key){return ['audio','source','height','audioLanguage','audioLabel','subtitleLanguage','subtitleLabel','subtitleOff'].indexOf(key)<0;}))throw new Error('Invalid show.');if(v.source && ['auto','cinejoy','vixsrc','lookmovie'].indexOf(v.source)<0)throw new Error('Invalid source.');if(v.height!==undefined && (!Number.isInteger(v.height)||v.height<0||v.height>4320))throw new Error('Invalid quality.');});
    if(!Array.isArray(data.watched)||data.watched.length>10000||data.watched.some(function(k){return ! /^(ani|luffy):[A-Za-z0-9_-]{1,200}:[0-9]{1,4}:[0-9.]{1,10}$/.test(k);}))throw new Error('Invalid watched flags.');
    Object.keys(lists).forEach(function(k){localStorage.setItem(k,JSON.stringify(lists[k]));});localStorage.setItem('showPreferences',JSON.stringify(shows));localStorage.setItem('watched',JSON.stringify(data.watched));
    if(p.subtitleSize!==undefined){subtitleSize=p.subtitleSize*2;localStorage.setItem('subtitleSize',String(subtitleSize));}if(p.subtitleColor!==undefined){subtitleColor='#'+(p.subtitleColor>>>0).toString(16).slice(-6);localStorage.setItem('subtitleColor',subtitleColor);}if(p.subtitleDelayMs!==undefined){subtitleDelay=p.subtitleDelayMs/1000;localStorage.setItem('subtitleDelay',String(subtitleDelay));}if(p.autoNext!==undefined){autoNext=p.autoNext;localStorage.setItem('autoNext',String(autoNext));}applySubtitles();
}
function backupService(method,parameters){return new Promise(function(resolve,reject){if(window.ANI_TEST_BACKUP)return window.ANI_TEST_BACKUP(method,parameters).then(resolve,reject);webOS.service.request('luna://dev.anidroid.tv.service',{method:method,parameters:parameters||{},onSuccess:resolve,onFailure:function(r){reject(new Error(r.errorText||'Backup unavailable.'));}});});}
function backupMessage(text){$('backupStatus').textContent=text;}
$('backupOptions').onclick=function(){$('backupSettings').hidden=false;backupMessage('');$('saveBackup').focus();};$('backupDone').onclick=function(){$('backupSettings').hidden=true;$('backupOptions').focus();};
$('saveBackup').onclick=function(){var data=exportLibrary();backupService('saveLibraryBackup',{data:data}).then(function(){backupMessage('Backup saved on this TV, outside the app installation.');}).catch(function(e){backupMessage(e.message);});};
$('restoreBackup').onclick=function(){backupService('loadLibraryBackup',{}).then(function(r){importLibrary(r.data);backupMessage('Lists and preferences restored.');}).catch(function(e){backupMessage(e.message);});};
$('exportBackupFile').onclick=function(){var data=exportLibrary();$('backupData').value=data;var link=document.createElement('a');link.href=URL.createObjectURL(new Blob([data],{type:'application/json'}));link.download='Ani-Droid-library.json';link.click();setTimeout(function(){URL.revokeObjectURL(link.href);},10000);backupMessage('Portable JSON shown below; file export depends on TV browser support.');};
$('importBackupFile').onclick=function(){$('backupFile').click();};$('backupFile').onchange=function(){var f=this.files[0];if(!f)return;if(f.size>2*1024*1024)return backupMessage('Backup is too large.');var reader=new FileReader();reader.onload=function(){try{importLibrary(reader.result);backupMessage('Backup restored.');}catch(e){backupMessage(e.message);}};reader.readAsText(f);};$('importBackupText').onclick=function(){try{importLibrary($('backupData').value);backupMessage('Backup restored.');}catch(e){backupMessage(e.message);}};
document.addEventListener('keydown',function(e){
    var key=e.keyCode,settingsOpen=!$('subtitleSettings').hidden,nextOpen=!$('nextUp').hidden,errorOpen=!$('videoError').hidden && state.playing,backupOpen=!$('backupSettings').hidden;if(key===461 || key===27){e.preventDefault();if(backupOpen){$('backupDone').click();return;}return settingsOpen?closeSubtitles():nextOpen?cancelNext():back();}
    if(state.playing && !settingsOpen && !nextOpen && !errorOpen && !backupOpen){if(key===40){e.preventDefault();openSubtitles();}else if(key===38){e.preventDefault();showHud();}else if(key===13 || key===19 || key===415){e.preventDefault();if(video.paused)video.play();else video.pause();showHud();}else if(key===37 || key===39){e.preventDefault();video.currentTime=Math.max(0,Math.min((video.duration||Infinity)-1,video.currentTime+(key===37?-10:10)));showHud();}return;}
    if([37,38,39,40].indexOf(key)<0)return;var active=document.activeElement;if(active.tagName==='SELECT' || ((active.tagName==='INPUT'||active.tagName==='TEXTAREA') && (key===37 || key===39)))return;
    var rect=active.getBoundingClientRect(),cx=rect.left+rect.width/2,cy=rect.top+rect.height/2,best=null,score=Infinity;
    Array.prototype.forEach.call((backupOpen?$('backupSettings'):settingsOpen?$('subtitleSettings'):nextOpen?$('nextUp'):errorOpen?$('videoError'):document).querySelectorAll('button,input,select'),function(el){if(el===active || el.disabled || !el.offsetParent)return;var r=el.getBoundingClientRect(),dx=r.left+r.width/2-cx,dy=r.top+r.height/2-cy;var forward=key===37?-dx:key===39?dx:key===38?-dy:dy;if(forward<=2)return;var cross=(key===37 || key===39)?Math.abs(dy):Math.abs(dx);var distance=forward+cross*3;if(distance<score){best=el;score=distance;}});
    if(best){e.preventDefault();best.focus();best.scrollIntoView({block:'nearest',inline:'nearest'});}
});
catalog(false);
}());
